// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: mbt_plugin.proto

package internalpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ArgType int32

const (
	ArgType_ARG_TYPE_UNKNOWN ArgType = 0
	ArgType_ARG_TYPE_ANY     ArgType = 1
)

// Enum value maps for ArgType.
var (
	ArgType_name = map[int32]string{
		0: "ARG_TYPE_UNKNOWN",
		1: "ARG_TYPE_ANY",
	}
	ArgType_value = map[string]int32{
		"ARG_TYPE_UNKNOWN": 0,
		"ARG_TYPE_ANY":     1,
	}
)

func (x ArgType) Enum() *ArgType {
	p := new(ArgType)
	*p = x
	return p
}

func (x ArgType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ArgType) Descriptor() protoreflect.EnumDescriptor {
	return file_mbt_plugin_proto_enumTypes[0].Descriptor()
}

func (ArgType) Type() protoreflect.EnumType {
	return &file_mbt_plugin_proto_enumTypes[0]
}

func (x ArgType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ArgType.Descriptor instead.
func (ArgType) EnumDescriptor() ([]byte, []int) {
	return file_mbt_plugin_proto_rawDescGZIP(), []int{0}
}

type StatusCode int32

const (
	StatusCode_STATUS_UNKNOWN          StatusCode = 0
	StatusCode_STATUS_OK               StatusCode = 1
	StatusCode_STATUS_NOT_IMPLEMENTED  StatusCode = 2
	StatusCode_STATUS_INVALID_ROLE     StatusCode = 3
	StatusCode_STATUS_INVALID_ACTION   StatusCode = 4
	StatusCode_STATUS_EXECUTION_FAILED StatusCode = 5
)

// Enum value maps for StatusCode.
var (
	StatusCode_name = map[int32]string{
		0: "STATUS_UNKNOWN",
		1: "STATUS_OK",
		2: "STATUS_NOT_IMPLEMENTED",
		3: "STATUS_INVALID_ROLE",
		4: "STATUS_INVALID_ACTION",
		5: "STATUS_EXECUTION_FAILED",
	}
	StatusCode_value = map[string]int32{
		"STATUS_UNKNOWN":          0,
		"STATUS_OK":               1,
		"STATUS_NOT_IMPLEMENTED":  2,
		"STATUS_INVALID_ROLE":     3,
		"STATUS_INVALID_ACTION":   4,
		"STATUS_EXECUTION_FAILED": 5,
	}
)

func (x StatusCode) Enum() *StatusCode {
	p := new(StatusCode)
	*p = x
	return p
}

func (x StatusCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusCode) Descriptor() protoreflect.EnumDescriptor {
	return file_mbt_plugin_proto_enumTypes[1].Descriptor()
}

func (StatusCode) Type() protoreflect.EnumType {
	return &file_mbt_plugin_proto_enumTypes[1]
}

func (x StatusCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatusCode.Descriptor instead.
func (StatusCode) EnumDescriptor() ([]byte, []int) {
	return file_mbt_plugin_proto_rawDescGZIP(), []int{1}
}

// ------------------ Common Value Representation ------------------
type Value struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Value_StrValue
	//	*Value_IntValue
	//	*Value_BoolValue
	//	*Value_MapValue
	//	*Value_ListValue
	//	*Value_SetValue
	Kind          isValue_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_mbt_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_mbt_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_mbt_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *Value) GetKind() isValue_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Value) GetStrValue() string {
	if x != nil {
		if x, ok := x.Kind.(*Value_StrValue); ok {
			return x.StrValue
		}
	}
	return ""
}

func (x *Value) GetIntValue() int64 {
	if x != nil {
		if x, ok := x.Kind.(*Value_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *Value) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Kind.(*Value_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *Value) GetMapValue() *MapValue {
	if x != nil {
		if x, ok := x.Kind.(*Value_MapValue); ok {
			return x.MapValue
		}
	}
	return nil
}

func (x *Value) GetListValue() *ListValue {
	if x != nil {
		if x, ok := x.Kind.(*Value_ListValue); ok {
			return x.ListValue
		}
	}
	return nil
}

func (x *Value) GetSetValue() *SetValue {
	if x != nil {
		if x, ok := x.Kind.(*Value_SetValue); ok {
			return x.SetValue
		}
	}
	return nil
}

type isValue_Kind interface {
	isValue_Kind()
}

type Value_StrValue struct {
	StrValue string `protobuf:"bytes,1,opt,name=str_value,json=strValue,proto3,oneof"`
}

type Value_IntValue struct {
	IntValue int64 `protobuf:"varint,2,opt,name=int_value,json=intValue,proto3,oneof"`
}

type Value_BoolValue struct {
	BoolValue bool `protobuf:"varint,3,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type Value_MapValue struct {
	MapValue *MapValue `protobuf:"bytes,4,opt,name=map_value,json=mapValue,proto3,oneof"`
}

type Value_ListValue struct {
	ListValue *ListValue `protobuf:"bytes,5,opt,name=list_value,json=listValue,proto3,oneof"`
}

type Value_SetValue struct {
	SetValue *SetValue `protobuf:"bytes,6,opt,name=set_value,json=setValue,proto3,oneof"`
}

func (*Value_StrValue) isValue_Kind() {}

func (*Value_IntValue) isValue_Kind() {}

func (*Value_BoolValue) isValue_Kind() {}

func (*Value_MapValue) isValue_Kind() {}

func (*Value_ListValue) isValue_Kind() {}

func (*Value_SetValue) isValue_Kind() {}

type MapValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*MapEntry            `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapValue) Reset() {
	*x = MapValue{}
	mi := &file_mbt_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapValue) ProtoMessage() {}

func (x *MapValue) ProtoReflect() protoreflect.Message {
	mi := &file_mbt_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapValue.ProtoReflect.Descriptor instead.
func (*MapValue) Descriptor() ([]byte, []int) {
	return file_mbt_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *MapValue) GetEntries() []*MapEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type MapEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *Value                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         *Value                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapEntry) Reset() {
	*x = MapEntry{}
	mi := &file_mbt_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapEntry) ProtoMessage() {}

func (x *MapEntry) ProtoReflect() protoreflect.Message {
	mi := &file_mbt_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapEntry.ProtoReflect.Descriptor instead.
func (*MapEntry) Descriptor() ([]byte, []int) {
	return file_mbt_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *MapEntry) GetKey() *Value {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *MapEntry) GetValue() *Value {
	if x != nil {
		return x.Value
	}
	return nil
}

type ListValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Value               `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListValue) Reset() {
	*x = ListValue{}
	mi := &file_mbt_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListValue) ProtoMessage() {}

func (x *ListValue) ProtoReflect() protoreflect.Message {
	mi := &file_mbt_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListValue.ProtoReflect.Descriptor instead.
func (*ListValue) Descriptor() ([]byte, []int) {
	return file_mbt_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *ListValue) GetItems() []*Value {
	if x != nil {
		return x.Items
	}
	return nil
}

type SetValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Value               `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetValue) Reset() {
	*x = SetValue{}
	mi := &file_mbt_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetValue) ProtoMessage() {}

func (x *SetValue) ProtoReflect() protoreflect.Message {
	mi := &file_mbt_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetValue.ProtoReflect.Descriptor instead.
func (*SetValue) Descriptor() ([]byte, []int) {
	return file_mbt_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *SetValue) GetItems() []*Value {
	if x != nil {
		return x.Items
	}
	return nil
}

// ------------------ Role / Action Execution ------------------
type RoleRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleName      string                 `protobuf:"bytes,1,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"` // e.g., "SlateDB", "ObjectStore"
	RoleId        int32                  `protobuf:"varint,2,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`      // e.g., instance index
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleRef) Reset() {
	*x = RoleRef{}
	mi := &file_mbt_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleRef) ProtoMessage() {}

func (x *RoleRef) ProtoReflect() protoreflect.Message {
	mi := &file_mbt_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleRef.ProtoReflect.Descriptor instead.
func (*RoleRef) Descriptor() ([]byte, []int) {
	return file_mbt_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *RoleRef) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *RoleRef) GetRoleId() int32 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

type Arg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ArgType                `protobuf:"varint,1,opt,name=type,proto3,enum=fizzbee.mbt.ArgType" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` // e.g., "key", "value"
	Value         *Value                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Arg) Reset() {
	*x = Arg{}
	mi := &file_mbt_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Arg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Arg) ProtoMessage() {}

func (x *Arg) ProtoReflect() protoreflect.Message {
	mi := &file_mbt_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Arg.ProtoReflect.Descriptor instead.
func (*Arg) Descriptor() ([]byte, []int) {
	return file_mbt_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *Arg) GetType() ArgType {
	if x != nil {
		return x.Type
	}
	return ArgType_ARG_TYPE_UNKNOWN
}

func (x *Arg) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Arg) GetValue() *Value {
	if x != nil {
		return x.Value
	}
	return nil
}

type Status struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          StatusCode             `protobuf:"varint,1,opt,name=code,proto3,enum=fizzbee.mbt.StatusCode" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // human-readable message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_mbt_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_mbt_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_mbt_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *Status) GetCode() StatusCode {
	if x != nil {
		return x.Code
	}
	return StatusCode_STATUS_UNKNOWN
}

func (x *Status) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Interval for execution times
type Interval struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartUnixNano int64                  `protobuf:"varint,1,opt,name=start_unix_nano,json=startUnixNano,proto3" json:"start_unix_nano,omitempty"`
	EndUnixNano   int64                  `protobuf:"varint,2,opt,name=end_unix_nano,json=endUnixNano,proto3" json:"end_unix_nano,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Interval) Reset() {
	*x = Interval{}
	mi := &file_mbt_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Interval) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Interval) ProtoMessage() {}

func (x *Interval) ProtoReflect() protoreflect.Message {
	mi := &file_mbt_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Interval.ProtoReflect.Descriptor instead.
func (*Interval) Descriptor() ([]byte, []int) {
	return file_mbt_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *Interval) GetStartUnixNano() int64 {
	if x != nil {
		return x.StartUnixNano
	}
	return 0
}

func (x *Interval) GetEndUnixNano() int64 {
	if x != nil {
		return x.EndUnixNano
	}
	return 0
}

// ------------------ RPC Messages ------------------
type InitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TestName      string                 `protobuf:"bytes,1,opt,name=test_name,json=testName,proto3" json:"test_name,omitempty"`
	Args          []*Arg                 `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitRequest) Reset() {
	*x = InitRequest{}
	mi := &file_mbt_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitRequest) ProtoMessage() {}

func (x *InitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mbt_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitRequest.ProtoReflect.Descriptor instead.
func (*InitRequest) Descriptor() ([]byte, []int) {
	return file_mbt_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *InitRequest) GetTestName() string {
	if x != nil {
		return x.TestName
	}
	return ""
}

func (x *InitRequest) GetArgs() []*Arg {
	if x != nil {
		return x.Args
	}
	return nil
}

type InitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecTime      *Interval              `protobuf:"bytes,1,opt,name=exec_time,json=execTime,proto3" json:"exec_time,omitempty"`
	Status        *Status                `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitResponse) Reset() {
	*x = InitResponse{}
	mi := &file_mbt_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitResponse) ProtoMessage() {}

func (x *InitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mbt_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitResponse.ProtoReflect.Descriptor instead.
func (*InitResponse) Descriptor() ([]byte, []int) {
	return file_mbt_plugin_proto_rawDescGZIP(), []int{10}
}

func (x *InitResponse) GetExecTime() *Interval {
	if x != nil {
		return x.ExecTime
	}
	return nil
}

func (x *InitResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type CleanupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CleanupRequest) Reset() {
	*x = CleanupRequest{}
	mi := &file_mbt_plugin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CleanupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanupRequest) ProtoMessage() {}

func (x *CleanupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mbt_plugin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanupRequest.ProtoReflect.Descriptor instead.
func (*CleanupRequest) Descriptor() ([]byte, []int) {
	return file_mbt_plugin_proto_rawDescGZIP(), []int{11}
}

type CleanupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecTime      *Interval              `protobuf:"bytes,1,opt,name=exec_time,json=execTime,proto3" json:"exec_time,omitempty"`
	Status        *Status                `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CleanupResponse) Reset() {
	*x = CleanupResponse{}
	mi := &file_mbt_plugin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CleanupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanupResponse) ProtoMessage() {}

func (x *CleanupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mbt_plugin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanupResponse.ProtoReflect.Descriptor instead.
func (*CleanupResponse) Descriptor() ([]byte, []int) {
	return file_mbt_plugin_proto_rawDescGZIP(), []int{12}
}

func (x *CleanupResponse) GetExecTime() *Interval {
	if x != nil {
		return x.ExecTime
	}
	return nil
}

func (x *CleanupResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type ExecuteActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          *RoleRef               `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	ActionName    string                 `protobuf:"bytes,2,opt,name=action_name,json=actionName,proto3" json:"action_name,omitempty"`
	Args          []*Arg                 `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteActionRequest) Reset() {
	*x = ExecuteActionRequest{}
	mi := &file_mbt_plugin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteActionRequest) ProtoMessage() {}

func (x *ExecuteActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mbt_plugin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteActionRequest.ProtoReflect.Descriptor instead.
func (*ExecuteActionRequest) Descriptor() ([]byte, []int) {
	return file_mbt_plugin_proto_rawDescGZIP(), []int{13}
}

func (x *ExecuteActionRequest) GetRole() *RoleRef {
	if x != nil {
		return x.Role
	}
	return nil
}

func (x *ExecuteActionRequest) GetActionName() string {
	if x != nil {
		return x.ActionName
	}
	return ""
}

func (x *ExecuteActionRequest) GetArgs() []*Arg {
	if x != nil {
		return x.Args
	}
	return nil
}

type ExecuteActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReturnValues  []*Value               `protobuf:"bytes,1,rep,name=return_values,json=returnValues,proto3" json:"return_values,omitempty"`
	ExecTime      *Interval              `protobuf:"bytes,2,opt,name=exec_time,json=execTime,proto3" json:"exec_time,omitempty"`
	Status        *Status                `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteActionResponse) Reset() {
	*x = ExecuteActionResponse{}
	mi := &file_mbt_plugin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteActionResponse) ProtoMessage() {}

func (x *ExecuteActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mbt_plugin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteActionResponse.ProtoReflect.Descriptor instead.
func (*ExecuteActionResponse) Descriptor() ([]byte, []int) {
	return file_mbt_plugin_proto_rawDescGZIP(), []int{14}
}

func (x *ExecuteActionResponse) GetReturnValues() []*Value {
	if x != nil {
		return x.ReturnValues
	}
	return nil
}

func (x *ExecuteActionResponse) GetExecTime() *Interval {
	if x != nil {
		return x.ExecTime
	}
	return nil
}

func (x *ExecuteActionResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

var File_mbt_plugin_proto protoreflect.FileDescriptor

const file_mbt_plugin_proto_rawDesc = "" +
	"\n" +
	"\x10mbt_plugin.proto\x12\vfizzbee.mbt\"\x93\x02\n" +
	"\x05Value\x12\x1d\n" +
	"\tstr_value\x18\x01 \x01(\tH\x00R\bstrValue\x12\x1d\n" +
	"\tint_value\x18\x02 \x01(\x03H\x00R\bintValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x03 \x01(\bH\x00R\tboolValue\x124\n" +
	"\tmap_value\x18\x04 \x01(\v2\x15.fizzbee.mbt.MapValueH\x00R\bmapValue\x127\n" +
	"\n" +
	"list_value\x18\x05 \x01(\v2\x16.fizzbee.mbt.ListValueH\x00R\tlistValue\x124\n" +
	"\tset_value\x18\x06 \x01(\v2\x15.fizzbee.mbt.SetValueH\x00R\bsetValueB\x06\n" +
	"\x04kind\";\n" +
	"\bMapValue\x12/\n" +
	"\aentries\x18\x01 \x03(\v2\x15.fizzbee.mbt.MapEntryR\aentries\"Z\n" +
	"\bMapEntry\x12$\n" +
	"\x03key\x18\x01 \x01(\v2\x12.fizzbee.mbt.ValueR\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.fizzbee.mbt.ValueR\x05value\"5\n" +
	"\tListValue\x12(\n" +
	"\x05items\x18\x01 \x03(\v2\x12.fizzbee.mbt.ValueR\x05items\"4\n" +
	"\bSetValue\x12(\n" +
	"\x05items\x18\x01 \x03(\v2\x12.fizzbee.mbt.ValueR\x05items\"?\n" +
	"\aRoleRef\x12\x1b\n" +
	"\trole_name\x18\x01 \x01(\tR\broleName\x12\x17\n" +
	"\arole_id\x18\x02 \x01(\x05R\x06roleId\"m\n" +
	"\x03Arg\x12(\n" +
	"\x04type\x18\x01 \x01(\x0e2\x14.fizzbee.mbt.ArgTypeR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12(\n" +
	"\x05value\x18\x03 \x01(\v2\x12.fizzbee.mbt.ValueR\x05value\"O\n" +
	"\x06Status\x12+\n" +
	"\x04code\x18\x01 \x01(\x0e2\x17.fizzbee.mbt.StatusCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"V\n" +
	"\bInterval\x12&\n" +
	"\x0fstart_unix_nano\x18\x01 \x01(\x03R\rstartUnixNano\x12\"\n" +
	"\rend_unix_nano\x18\x02 \x01(\x03R\vendUnixNano\"P\n" +
	"\vInitRequest\x12\x1b\n" +
	"\ttest_name\x18\x01 \x01(\tR\btestName\x12$\n" +
	"\x04args\x18\x02 \x03(\v2\x10.fizzbee.mbt.ArgR\x04args\"o\n" +
	"\fInitResponse\x122\n" +
	"\texec_time\x18\x01 \x01(\v2\x15.fizzbee.mbt.IntervalR\bexecTime\x12+\n" +
	"\x06status\x18\x02 \x01(\v2\x13.fizzbee.mbt.StatusR\x06status\"\x10\n" +
	"\x0eCleanupRequest\"r\n" +
	"\x0fCleanupResponse\x122\n" +
	"\texec_time\x18\x01 \x01(\v2\x15.fizzbee.mbt.IntervalR\bexecTime\x12+\n" +
	"\x06status\x18\x02 \x01(\v2\x13.fizzbee.mbt.StatusR\x06status\"\x87\x01\n" +
	"\x14ExecuteActionRequest\x12(\n" +
	"\x04role\x18\x01 \x01(\v2\x14.fizzbee.mbt.RoleRefR\x04role\x12\x1f\n" +
	"\vaction_name\x18\x02 \x01(\tR\n" +
	"actionName\x12$\n" +
	"\x04args\x18\x03 \x03(\v2\x10.fizzbee.mbt.ArgR\x04args\"\xb1\x01\n" +
	"\x15ExecuteActionResponse\x127\n" +
	"\rreturn_values\x18\x01 \x03(\v2\x12.fizzbee.mbt.ValueR\freturnValues\x122\n" +
	"\texec_time\x18\x02 \x01(\v2\x15.fizzbee.mbt.IntervalR\bexecTime\x12+\n" +
	"\x06status\x18\x03 \x01(\v2\x13.fizzbee.mbt.StatusR\x06status*1\n" +
	"\aArgType\x12\x14\n" +
	"\x10ARG_TYPE_UNKNOWN\x10\x00\x12\x10\n" +
	"\fARG_TYPE_ANY\x10\x01*\x9c\x01\n" +
	"\n" +
	"StatusCode\x12\x12\n" +
	"\x0eSTATUS_UNKNOWN\x10\x00\x12\r\n" +
	"\tSTATUS_OK\x10\x01\x12\x1a\n" +
	"\x16STATUS_NOT_IMPLEMENTED\x10\x02\x12\x17\n" +
	"\x13STATUS_INVALID_ROLE\x10\x03\x12\x19\n" +
	"\x15STATUS_INVALID_ACTION\x10\x04\x12\x1b\n" +
	"\x17STATUS_EXECUTION_FAILED\x10\x052\xf4\x01\n" +
	"\x17FizzBeeMbtPluginService\x12;\n" +
	"\x04Init\x12\x18.fizzbee.mbt.InitRequest\x1a\x19.fizzbee.mbt.InitResponse\x12D\n" +
	"\aCleanup\x12\x1b.fizzbee.mbt.CleanupRequest\x1a\x1c.fizzbee.mbt.CleanupResponse\x12V\n" +
	"\rExecuteAction\x12!.fizzbee.mbt.ExecuteActionRequest\x1a\".fizzbee.mbt.ExecuteActionResponseB5Z3github.com/fizzbee-io/fizzbee/mbt/lib/go/internalpbb\x06proto3"

var (
	file_mbt_plugin_proto_rawDescOnce sync.Once
	file_mbt_plugin_proto_rawDescData []byte
)

func file_mbt_plugin_proto_rawDescGZIP() []byte {
	file_mbt_plugin_proto_rawDescOnce.Do(func() {
		file_mbt_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mbt_plugin_proto_rawDesc), len(file_mbt_plugin_proto_rawDesc)))
	})
	return file_mbt_plugin_proto_rawDescData
}

var file_mbt_plugin_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_mbt_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_mbt_plugin_proto_goTypes = []any{
	(ArgType)(0),                  // 0: fizzbee.mbt.ArgType
	(StatusCode)(0),               // 1: fizzbee.mbt.StatusCode
	(*Value)(nil),                 // 2: fizzbee.mbt.Value
	(*MapValue)(nil),              // 3: fizzbee.mbt.MapValue
	(*MapEntry)(nil),              // 4: fizzbee.mbt.MapEntry
	(*ListValue)(nil),             // 5: fizzbee.mbt.ListValue
	(*SetValue)(nil),              // 6: fizzbee.mbt.SetValue
	(*RoleRef)(nil),               // 7: fizzbee.mbt.RoleRef
	(*Arg)(nil),                   // 8: fizzbee.mbt.Arg
	(*Status)(nil),                // 9: fizzbee.mbt.Status
	(*Interval)(nil),              // 10: fizzbee.mbt.Interval
	(*InitRequest)(nil),           // 11: fizzbee.mbt.InitRequest
	(*InitResponse)(nil),          // 12: fizzbee.mbt.InitResponse
	(*CleanupRequest)(nil),        // 13: fizzbee.mbt.CleanupRequest
	(*CleanupResponse)(nil),       // 14: fizzbee.mbt.CleanupResponse
	(*ExecuteActionRequest)(nil),  // 15: fizzbee.mbt.ExecuteActionRequest
	(*ExecuteActionResponse)(nil), // 16: fizzbee.mbt.ExecuteActionResponse
}
var file_mbt_plugin_proto_depIdxs = []int32{
	3,  // 0: fizzbee.mbt.Value.map_value:type_name -> fizzbee.mbt.MapValue
	5,  // 1: fizzbee.mbt.Value.list_value:type_name -> fizzbee.mbt.ListValue
	6,  // 2: fizzbee.mbt.Value.set_value:type_name -> fizzbee.mbt.SetValue
	4,  // 3: fizzbee.mbt.MapValue.entries:type_name -> fizzbee.mbt.MapEntry
	2,  // 4: fizzbee.mbt.MapEntry.key:type_name -> fizzbee.mbt.Value
	2,  // 5: fizzbee.mbt.MapEntry.value:type_name -> fizzbee.mbt.Value
	2,  // 6: fizzbee.mbt.ListValue.items:type_name -> fizzbee.mbt.Value
	2,  // 7: fizzbee.mbt.SetValue.items:type_name -> fizzbee.mbt.Value
	0,  // 8: fizzbee.mbt.Arg.type:type_name -> fizzbee.mbt.ArgType
	2,  // 9: fizzbee.mbt.Arg.value:type_name -> fizzbee.mbt.Value
	1,  // 10: fizzbee.mbt.Status.code:type_name -> fizzbee.mbt.StatusCode
	8,  // 11: fizzbee.mbt.InitRequest.args:type_name -> fizzbee.mbt.Arg
	10, // 12: fizzbee.mbt.InitResponse.exec_time:type_name -> fizzbee.mbt.Interval
	9,  // 13: fizzbee.mbt.InitResponse.status:type_name -> fizzbee.mbt.Status
	10, // 14: fizzbee.mbt.CleanupResponse.exec_time:type_name -> fizzbee.mbt.Interval
	9,  // 15: fizzbee.mbt.CleanupResponse.status:type_name -> fizzbee.mbt.Status
	7,  // 16: fizzbee.mbt.ExecuteActionRequest.role:type_name -> fizzbee.mbt.RoleRef
	8,  // 17: fizzbee.mbt.ExecuteActionRequest.args:type_name -> fizzbee.mbt.Arg
	2,  // 18: fizzbee.mbt.ExecuteActionResponse.return_values:type_name -> fizzbee.mbt.Value
	10, // 19: fizzbee.mbt.ExecuteActionResponse.exec_time:type_name -> fizzbee.mbt.Interval
	9,  // 20: fizzbee.mbt.ExecuteActionResponse.status:type_name -> fizzbee.mbt.Status
	11, // 21: fizzbee.mbt.FizzBeeMbtPluginService.Init:input_type -> fizzbee.mbt.InitRequest
	13, // 22: fizzbee.mbt.FizzBeeMbtPluginService.Cleanup:input_type -> fizzbee.mbt.CleanupRequest
	15, // 23: fizzbee.mbt.FizzBeeMbtPluginService.ExecuteAction:input_type -> fizzbee.mbt.ExecuteActionRequest
	12, // 24: fizzbee.mbt.FizzBeeMbtPluginService.Init:output_type -> fizzbee.mbt.InitResponse
	14, // 25: fizzbee.mbt.FizzBeeMbtPluginService.Cleanup:output_type -> fizzbee.mbt.CleanupResponse
	16, // 26: fizzbee.mbt.FizzBeeMbtPluginService.ExecuteAction:output_type -> fizzbee.mbt.ExecuteActionResponse
	24, // [24:27] is the sub-list for method output_type
	21, // [21:24] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_mbt_plugin_proto_init() }
func file_mbt_plugin_proto_init() {
	if File_mbt_plugin_proto != nil {
		return
	}
	file_mbt_plugin_proto_msgTypes[0].OneofWrappers = []any{
		(*Value_StrValue)(nil),
		(*Value_IntValue)(nil),
		(*Value_BoolValue)(nil),
		(*Value_MapValue)(nil),
		(*Value_ListValue)(nil),
		(*Value_SetValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mbt_plugin_proto_rawDesc), len(file_mbt_plugin_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mbt_plugin_proto_goTypes,
		DependencyIndexes: file_mbt_plugin_proto_depIdxs,
		EnumInfos:         file_mbt_plugin_proto_enumTypes,
		MessageInfos:      file_mbt_plugin_proto_msgTypes,
	}.Build()
	File_mbt_plugin_proto = out.File
	file_mbt_plugin_proto_goTypes = nil
	file_mbt_plugin_proto_depIdxs = nil
}
