#!/bin/bash

SCRIPT_DIR="$(dirname "$(readlink -f "${BASH_SOURCE[0]:-$0}")")"
WORKING_DIR="$(pwd)"

echo $SCRIPT_DIR
echo $WORKING_DIR

usage() {
  echo "Usage: $0 [-x|--simulation] [--seed int64Number] [-- max_runs intNumber] filename"
  exit 1
}

# Initialize variables
simulation=false
seed=0
max_runs=0

# Parse options
while [[ "$1" =~ ^- ]]; do
  case $1 in
    -x | --simulation )
      simulation=true
      shift
      ;;
    --seed )
      if [[ -n "$2" ]] && [[ "$2" =~ ^[0-9]+$ ]]; then
        seed="$2"
        shift 2
      else
        echo "Error: --seed requires a numeric value." 1>&2
        usage
      fi
      ;;
    --max_runs )
      if [[ -n "$2" ]] && [[ "$2" =~ ^[0-9]+$ ]]; then
        max_runs="$2"
        shift 2
      else
        echo "Error: --max_runs requires a numeric value." 1>&2
        usage
      fi
      ;;
    --internal_profile )
      internal_profile=true
      shift
      ;;
    -h | --help )
      usage
      ;;
    * )
      echo "Invalid option: $1" 1>&2
      usage
      ;;
  esac
done

# Check for the required positional argument
if [ -z "$1" ]; then
  echo "Error: filename is required" 1>&2
  usage
fi

input_filename=$1

# Example usage of the parsed options and arguments
if [ "$simulation" = true ]; then
  echo "Simulation mode is enabled"
fi

input_filename=$1

# Set the paths for the binaries relative to the script directory
PARSER_BIN="$SCRIPT_DIR/parser/parser_bin"
FIZZBEE_BIN="$SCRIPT_DIR/fizzbee"

# Call the first binary and redirect output to a temporary file
temp_output=$(mktemp)
if ! "$PARSER_BIN" "$input_filename" > "$temp_output"; then
    echo "Error: Compilation failed"
    echo "Logs at $temp_output"
    exit 1
fi

# Create the JSON filename by replacing the extension
json_filename="${input_filename%.*}.json"

echo "Model checking" $json_filename

# Prepare arguments for the Go binary
args=()
if [ "$simulation" = true ]; then
  args+=("--simulation")
fi
if [ "$internal_profile" = true ]; then
  args+=("--internal_profile")
fi
if [ "$seed" -ne 0 ]; then
  args+=("--seed" "$seed")
fi
if [ "$max_runs" -ne 0 ]; then
  args+=("--max_runs" "$max_runs")
fi

args+=("$json_filename")


# Run the second command with the JSON filename
"$FIZZBEE_BIN" "${args[@]}"

# Clean up the temporary file
rm "$temp_output"

